name: admin_vlh
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.2
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  intl: ^0.19.0
  http: ^1.1.0
  syncfusion_flutter_charts: ^31.2.5
  google_fonts: ^6.0.0
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/