name: vanita_food_app
description: A new Flutter project for Vanita Lunch Home.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true